name = "Fresh"
author = "redraskal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e9ff742072fc541be0fa455db45f0193460f23fd543737cec82d3d6776d46b2"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
