name = "Fresh"
author = "redraskal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4afe27d7c2f6492a231ce98074fc58399e5e4c4e8104e533defbd89dc2435c58"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
