name: Build
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup packwiz
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.2'
      - run: go install github.com/packwiz/packwiz@latest
      - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
      - name: Build
      - run: packwiz cf export
